# настройки запуска
run:
  # значение конкурентности устанавливаем по количеству CPU
  concurrency: 4

  # анализ не должен превышать
  timeout: 1m

  # выводить "exit-code" при наличии хотя бы одного сообщения
  issues-exit-code: 1

  # не включать анализ тестов
  tests: true

# список линтеров
linters:
  disable-all: true
  enable:
    - gofmt # форматирование кода (пробелы, отступы, скобки)
    - goimports # обновление списка imports
    - govet # общий анализ возможных багов
    - goconst # нахождение строк, которые следует вынести в константы
    - funlen # поиск слишком крупных функций
    - bodyclose # проверка на незакрытые body после чтения тела ответа
    - errcheck # проверка на обработку всех ошибок
    - exportloopref # детектирование экспорта указателя на переменную внутри цикла

# настройки отдельных линтеров
linters-settings:
  goimports:
    # указываем префикс локальных импортов, они будут группироваться
    local-prefixes: github.com/MaxFando/application-design
  goconst:
    # goconst находит строки не меньше 2 символов, которые встречаются хотя бы 2 раза
    min-len: 2
    min-occurrences: 2
  funlen:
    # функция помечается длинной если она больше 120 строк кода либо больше 50 операций
    lines: 120
    statements: 50

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - goimports
        - goconst